### ISSUE TITLE
USER STORY: <Search for a product>

### ISSUE THREAD

**Issue by soukasamadi** [soukasamadi/CaffeineMoment#3]
As a **Site User** I can **search for a speciifc product** so that **I can easily find and select a product**

**Acceptance Criteria:**

- Make it easy for the users to search for a product.

**Tasks:**

- [ ] Provide a view for the search.
- [ ] Display all matches products with the typed user text.
- [ ] Diplay a message if there is no product found.
