### ISSUE TITLE
USER STORY: <Sort Products>

### ISSUE THREAD

**Issue by soukasamadi** [soukasamadi/CaffeineMoment#4]
As a **Site User** I can **Sort products** so that **I can easily identify the best product for me**

**Acceptance Criteria:**

- Sort product by different options and display the number of available product in each sort type.

**Tasks:**

- [ ] Sort product by price.
- [ ] Sort product by rating.
- [ ] Sort product by category.
