### ISSUE TITLE
USER STORY: <Login System>

### ISSUE THREAD

**Issue by soukasamadi** [soukasamadi/CaffeineMoment#5]
As a **Registred User** I can **easity login and logout** so that **I can access my personal informations**

**Acceptance Criteria:**

- Secure login system.
-Display login button.
- Display logout instead of login while user is logged in.

**Tasks:**

- [ ] Add login system.
- [ ] Add login and logout buttons to the menu.
- [ ] Display the right login or logout btn deppending on the user status.
- [ ] Allow the loged in user to access and update his profile.
- [ ] Successful logout system
