### ISSUE TITLE
USER STORY: <Shopping bag>

### ISSUE THREAD

**Issue by soukasamadi** [soukasamadi/CaffeineMoment#9]
As a **Logegd in user** I can **add and view items on my shopping bag** so that **identify the total cost**

**Acceptance Criteria:**

- Allow the user to add products to the bag and update them.

**Tasks:**

- [x] User can add products to the shopping bag.
- [x] User can update the products on the bag.
- [x] User can delete products on the bg.
- [x] User can edit the quantity of each product.
- [x] show the total cost.
